Warsztaty4/Warsztaty4/urls.py
from django.contrib import admin
from django.urls import path, re_path
from mail_box.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('new', NewPerson.as_view()),
    re_path(r'^modify/(?P<id>\d+)', Modify.as_view()),
    re_path(r'^delete/(?P<id>\d+)', Delete.as_view()),
    re_path(r'^show/(?P<id>\d+)', Single.as_view()),
    path('', Basic.as_view()),
    re_path(r'^addAddress/(?P<id>\d+)$', AddAddress.as_view()),
    re_path(r'^addEmail/(?P<id>\d+)$', AddEmail.as_view()),
    re_path(r'^addPhone/(?P<id>\d+)$', AddPhone.as_view()),
    path('new_group', NewGroup.as_view()),
    path('group_list', GroupList.as_view()),
    re_path(r'^show_group/(?P<id>\d+)$', Groups.as_view()),
    re_path(r'^addMember/(?P<id>\d+)$', AddMember.as_view()),
    #path('search', Search.as_view()),
]

Warsztaty4/mail_box/models.py
from django.db import models

PHONE_CHOICE = (
    (0, 'brak informacji'),
    (1, 'komórkowy'),
    (2, 'domowy'),
    (3, 'służbowy'),
    (4, 'inny')
)

EMAIL_CHOICE = (
    (0, 'brak informacji'),
    (1, 'prywatny'),
    (2, 'służbowy'),
    (3, 'inny')
)


class Person(models.Model):
    name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    description = models.CharField(max_length=128, null=True)
    #image = models.ImageField(upload_to="home/witek/Desktop/Warsztaty4/Warsztaty4/Warsztaty4/mail_box/Photos/", blank=True)
    adres = models.ForeignKey("Address", on_delete=models.PROTECT, null=True)


class Address(models.Model):
    city = models.CharField(max_length=64)
    street = models.CharField(max_length=64, null=True)
    house_no = models.CharField(max_length=64, null=True)
    flat_no = models.CharField(max_length=64, null=True)


class Phone(models.Model):
    ph_number = models.CharField(max_length=32)
    ph_type = models.IntegerField(choices=PHONE_CHOICE, default=0)
    owner = models.ForeignKey(Person, on_delete=models.CASCADE)


class Email(models.Model):
    email_address = models.CharField(max_length=64)
    email_type = models.IntegerField(choices=EMAIL_CHOICE, default=0)
    e_owner = models.ForeignKey(Person, on_delete=models.CASCADE)


class Group(models.Model):
    name = models.CharField(max_length=64)
    persons = models.ManyToManyField(Person)

Warsztaty4/mail_box/views.py
from django.shortcuts import render
from django.views import View
from .models import *
from django.http import HttpResponse, Http404, HttpResponseRedirect


class NewPerson(View):
    def get(self, request):
        return render(request, "new_person.html")

    def post(self, request):
        name = request.POST.get('name')
        last_name = request.POST.get('last_name')
        description = request.POST.get('description')
        #image = request.POST.get('image')
        new_person = Person.objects.create(name=f'{name}', last_name=f'{last_name}', description=f'{description}')
        msg = "Dodano nową osobę"
        return render(request, "base.html", locals())


class NewGroup(View):
    def get(self, request):
        return render(request, "new_group.html")

    def post(self, request):
        name = request.POST.get('name')
        new_group = Group.objects.create(name=name)
        msg = "Dodano nową grupę"
        return render(request, "base.html", locals())


class Modify(View):
    def get(self, request, id):
        person = Person.objects.get(pk=id)
        cnx = {
            "name": person.name,
            "last_name": person.last_name,
            "description": person.description,
            "id": person.id,
        }
        return render(request, "modify_person.html", cnx)

    def post(self, request, id):
        name = request.POST.get('name')
        last_name = request.POST.get('last_name')
        description = request.POST.get('description')
        # image = request.POST.get('image')
        new_person = Person.objects.get(pk=id)
        new_person.name = name
        new_person.last_name = last_name
        new_person.description = description
        new_person.save()
        return HttpResponseRedirect(f'/show/{id}')


class AddAddress(View):
    def post(self, request, id):
        city = request.POST.get('city')
        street = request.POST.get('street')
        house_no = request.POST.get('house_no')
        flat_no = request.POST.get('flat_no')
        new_address = Address.objects.create\
            (city=f'{city}', street=f'{street}', house_no=f'{house_no}', flat_no=f'{flat_no}')
        contact = Person.objects.get(pk=id)
        contact.adres = new_address
        contact.save()
        people = Person.objects.all()
        return HttpResponseRedirect("/")


class AddEmail(View):
    def post(self, request, id):
        email_address = request.POST.get('email_address')
        email_type = request.POST.get('email_type')
        contact = Person.objects.get(pk=id)
        new_address = Email()
        new_address.email_address = email_address
        new_address.email_type = email_type
        new_address.e_owner = contact
        new_address.save()
        people = Person.objects.all()
        return HttpResponseRedirect("/")


class AddPhone(View):
    def post(self, request, id):
        ph_number = request.POST.get('ph_number')
        ph_type = request.POST.get('ph_type')
        contact = Person.objects.get(id=id)
        new_phone = Phone()
        new_phone.ph_number = ph_number
        new_phone.ph_type = ph_type
        new_phone.owner = contact
        new_phone.save()
        people = Person.objects.all()
        return HttpResponseRedirect("/")


class Delete(View):
    def get(self, request, id):
        person = Person.objects.get(pk=id)
        person.delete()
        return HttpResponseRedirect('/')


class Single(View):
    def get(self, request, id):
        person = Person.objects.get(pk=id)
        cnx = {
            "name": person.name,
            "last_name": person.last_name,
            "description": person.description,
            "address": person.adres,
            "id": person.id,
            "phone": person.phone_set.all(),
            "email": person.email_set.all(),
        }
        return render(request, "single.html", cnx)


class Groups(View):
    def get(self, request, id):
        show_group = Group.objects.get(pk=id)
        cnx = {
            "name": show_group.name,
            "person": show_group.persons.all(),
        }
        return render(request, "show_group.html", cnx)


class AddMember(View):
    def get(self, request, id):
        groups = Group.objects.all()
        return render(request, "add_member.html", locals())

    def post(self, request, id):
        name = request.POST.getlist('name')
        member = Person.objects.get(pk=id)
        for g_id in name:
            i = Group.objects.get(id=int(g_id))
            i.persons.add(member)
        people = Person.objects.all()
        msg = "Dodano"
        return render(request, "base.html", locals())


class GroupList(View):
    def get(self, request):
        group = Group.objects.all()
        return render(request, "group_list.html", locals())

    def post(self, request):
        search = request.POST.get('search')
        data = search.split()
        l_data = [x.lower() for x in data]
        person = Person.objects.all()
        group = Group.objects.all()
        person_list = []
        res = []
        for d in l_data:
            for p in person:
                if d == p.name.lower() or d == p.last_name.lower():
                    person_list.append(p)
        for g in group:
            for a in g.persons.all():
                for p in person_list:
                    if p == a:
                        if g not in res:
                            res.append(g)
        group = res
        return render(request, "search.html", locals())


class Basic(View):
    def get(self, request):
        people = Person.objects.all().order_by('last_name')
        return render(request, "person.html", locals())

Warsztaty4/mail_box/templates/add_member.html
{% extends "base.html" %}

{% block content %}
<table>
<form action="" method="POST">
 {% csrf_token %}
{% for p in groups %}
<input type="checkbox" name="name" value="{{ p.id }}">{{ p.name }}<br>
{% endfor %}
<input type="submit" value="Dodaj">
</form></table></form>
{% endblock %}

Warsztaty4/mail_box/templates/base.html
<!doctype html>
<html>
        <head>
        <meta charset = "utf-8">
        </head>
        <title>
        {% block title %}

        {% endblock %}
        </title>
        </head>
    <body>
        {%  block header %}

        {% endblock %}
        <div> {{ msg }} </div>

        {% block content %}

        {% endblock %}
        {% block footer %}
        <div style="{% block footer_style %}{% endblock %}">
        	Copyright by XXX
        </div>
        {% endblock %}
    </body>
</html>

Warsztaty4/mail_box/templates/group_list.html
{% extends "base.html" %}

{% block header %}
    <h1>Lista grup</h1>
{% endblock %}

{% block content %}
    <form action="/group_list" method="POST">
    <input type="text" name="search" placeholder="Podaj imię lub nazwisko">
    <input type="submit" value="Wyszukaj">
    <table>
            <tr><th>Nazwa grupy</th></tr>
        {% for g in group %}
                <td><a href = show_group/{{ g.id }}> {{ g.name }} </a>
            </td></tr>
            {% endfor %}
        </table>
    </form>
{% endblock %}

Warsztaty4/mail_box/templates/modify_person.html
{% extends "base.html" %}

{% block header %}
<h1>Zmodyfikuj osobę</h1>
{% endblock %}


{% block content %}
<form action="" method="POST">
   {% csrf_token %}
   <label> Imię:
       <input type="text"
              name="name"
       value="{{ name }}">
   </label><br>
    <label> Nazwisko:
       <input type="text"
              name="last_name"
       value="{{ last_name }}">
   </label><br>
   <label> Opis:
       <input type="text"
              name="description"
       value="{{ description }}">
   </label><br>
   <label>
       <input type="submit" value="Zmień">
   </label>
</form>

    <form action="/addAddress/{{ id }}" method="POST">
   {% csrf_token %}
   <label> Miasto:
       <input type="text"
              name="city"
       value="{{ city }}">
   </label><br>
    <label> Ulica:
       <input type="text"
              name="street"
       value="{{ street }}">
   </label><br>
   <label> Nr domu:
       <input type="text"
              name="house_no"
       value="{{ house_no }}">
   </label><br>
        <label> Nr mieszkania:
       <input type="text"
              name="flat_no"
       value="{{ flat_no }}">
   </label><br>
   <label>
       <input type="submit" value="Zmień">
   </label>
</form>

    <form action="/addEmail/{{ id }}" method="POST">
   {% csrf_token %}
   <label> Email:
       <input type="text"
              name="email_address"
       value="{{ email_address }}">
   </label><br>
    <select name="email_type">
       <option
               value="0">brak informacji</option>
            <option
               value="1">prywatny</option>
            <option
               value="2">służbowy</option>
            <option
               value="3">inny</option>
            </select><br>
       <input type="submit" value="Zmień">
   </label>
</form>

    <form action="/addPhone/{{ id }}" method="POST">
   {% csrf_token %}
   <label> Numer telefonu:
       <input type="text"
              name="ph_number"
       value="{{ ph_number }}">
   </label><br>
    <label> Typ:
        <select name="ph_type">
       <option
               value="0">brak informacji</option>
            <option
               value="1">komórkowy</option>
            <option
               value="2">domowy</option>
            <option
               value="3">służbowy</option>
            <option
               value="4">inny</option>
            </select>
   </label><br>
        <label>
       <input type="submit" value="Zmień">
   </label>
</form>
{% endblock %}

Warsztaty4/mail_box/templates/new_group.html
{% extends "base.html" %}

{% block header %}
<h1>Dodaj nową grupę</h1>
{% endblock %}


{% block content %}
<form action="", method="POST">
   {% csrf_token %}
   <label> Nazwa grupy:
       <input type="text"
              name="name">
   </label><br>
   <label>
       <input type="submit" value="Dodaj">
   </label>
</form>
{% endblock %}

Warsztaty4/mail_box/templates/new_person.html
{% extends "base.html" %}

{% block header %}
<h1>Dodaj nową osobę</h1>
{% endblock %}


{% block content %}
<form action="", method="POST">
   {% csrf_token %}
   <label> Imię:
       <input type="text"
              name="name">
   </label><br>
    <label> Nazwisko:
       <input type="text"
              name="last_name">
   </label><br>
   <label> Opis:
       <input type="text"
              name="description">
   </label><br>
   <label>
       <input type="submit" value="Dodaj">
   </label>
</form>
{% endblock %}

Warsztaty4/mail_box/templates/person.html
{% extends "base.html" %}

{% block header %}
    <h1>Lista osób</h1>
{% endblock %}

{% block content %}
    <table>
            <tr><th>Imię</th><th>Nazwisko</th><th>Opis</th></tr>
            {% for r in people %}
                <td><a href = show/{{ r.id }}> {{ r.name }} </a>
             </td><td>
                {{ r.last_name }}
                </td><td>
                {{ r.description }}
                </td><td>
            {{ r.city }}
            </td><td>
            {{ r.street }}
            </td><td>
            {{ r.house_no }}
            </td><td>
            {{ r.flat_no }}
            </td><td>
                <a href = modify/{{r.id}}> Zmień </a>
            </td><td>
                <a href = delete/{{r.id}}> Usuń </a>
            </td></tr>
            {% endfor %}
        </table>
    <form action="/search" ><input type="submit" value="Szukaj"> </form><br>
    <form action="/new" ><input type="submit" value="Dodaj nową osobę"> </form><br>
    <form action="/group_list" ><input type="submit" value="Lista grup"> </form><br>
    <form action="/new_group" ><input type="submit" value="Dodaj nową grupę"> </form>
{% endblock %}

Warsztaty4/mail_box/templates/search.html
{% extends "base.html" %}

{% block header %}
    <h1>{{  }}</h1>
{% endblock %}

{% block content %}
    <form action="/group_list" method="POST">
    <input type="text" name="search" placeholder="Podaj imię lub nazwisko">
    <input type="submit" value="Wyszukaj">
    <table>
            <tr><th>Nazwa grupy</th></tr>
        {% for g in group %}
                <td><a href = show_group/{{ g.id }}> {{ g.name }} </a>
            </td></tr>
            {% endfor %}
        </table>
    </form>
{% endblock %}

Warsztaty4/mail_box/templates/show_group.html
{% extends "base.html" %}

{% block content %}
   <table>
       <tr><th>Nazwa</th><th>Imię</th><th>Nazwisko</th></tr>
       <tr><td>{{ name }}</td>
       {% for g in person %}
    <td>{{ g.name }}</td><td>{{ g.last_name }}</td>
    {% endfor %}</tr>
    </table><br>

   <form action="/" ><input type="submit" value="Wróć na stronę główną"> </form><br>
{% endblock %}

Warsztaty4/mail_box/templates/single.html
{% extends "base.html" %}

{% block content %}
   <table>
       <tr><th>Nazwa</th><th>Nazwisko</th><th>Opis</th></tr>
       <tr><td>{{ name }}</td><td>{{ last_name }}</td><td>{{ description }}</td></tr>
   </table><br>
    <table>
    <tr><th>Miasto</th><th>Ulica</th><th>Nr domu</th><th>Nr ulicy</th></tr>
    {% for a in adres %}
        <tr><td>{{ a.city }}</td><td>{{ a.street }}</td><td>{{ a.house_no }}</td><td>{{ a.flat_no }}</td></tr>
    {% endfor %}
    </table><br>
    <table>
    <tr><th>Numer telefonu</th><th>Typ telefonu</th></tr>
        {% for p in phone %}
    <tr><td>{{ p.ph_number }}</td><td>{{ p.get_ph_type_display }}</td></tr>
    {% endfor %}
    </table><br>
    <table>
    <tr><th>Adres email</th><th>Typ email</th></tr>
        {% for e in email %}
    <tr><td>{{ e.email_address }}</td><td>{{ e.get_email_type_display }}</td></tr>
    {%  endfor %}
    </table><br>

<form action="/addMember/{{ id }}" ><input type="submit" value="Dodaj do grupy"> </form><br>
   <form action="/" ><input type="submit" value="Wróć na stronę główną"> </form><br>
    <form action="/modify/{{ id }}" ><input type="submit" value="Modyfikuj informacje"> </form>
{% endblock %}